version: '3.3'
services:
  RegisterAndLogin:
    hostname: postgres-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '7374:5432'
    volumes:
      - my-db:/var/lib/postgresql
volumes:
  my-db: